### PR TITLE
Serde Protojson support

### LINKED ISSUE #165: ProtoJSON regression in Serde derives
We noticed a regression since #95 (not sure where or when exactly) that results in the `ibc-proto` types having broken `Serialize`, `Deserialize` implementations.

Test case:

- https://github.com/penumbra-zone/penumbra/blob/timeout-bug/crates/wasm/tests/test_deserialize.rs fails (but should pass)
- https://github.com/penumbra-zone/penumbra/blob/timeout-bug-snakecase/crates/wasm/tests/test_deserialize.rs passes (but should fail)

In that test code, the `Ics20Withdrawal` is a Penumbra-specific action that includes an IBC `TimeoutHeight`.  Our Proto build configuration place the `ibc-proto` types as the generated code for `ibc` proto messages, so its `Serialize` and `Deserialize` impls forward to the ones in this crate.

Looking at the code in https://github.com/cosmos/ibc-proto-rs/blob/main/tools/proto-compiler/src/cmd/compile.rs , I don't see any invocations of `pbjson_build` at all, I'm not sure what happened since #95.

### PR DESCRIPTION
**Pull request by grod220**
Fixes #165

Note:
- Some types needed to be excluded given they depend on tendermint-proto which also does not implement protojson.

### CODE REVIEW

File: tools/proto-compiler/src/cmd/compile.rs
Comment (grod220) [inline tools/proto-compiler/src/cmd/compile.rs:1]: The main thing to review

**Comment by grod220** [comment]
Thanks for reviewing when you get a chance @romac 🙏

**Comment by romac** [comment]
Thanks a lot for the PR, looks good to me!

I am  leaving the last word to @Farhad-Shabani in case this impacts ibc-rs.

File: Cargo.toml [hunk 1]
```diff
@@ -32,11 +32,11 @@ prost           = { version = "0.12.3", default-features = false, features = ["p
 bytes           = { version = "1.2",  default-features = false }
 tonic           = { version = "0.10",  default-features = false, optional = true }
 serde           = { version = "1.0",  default-features = false, optional = true }
-schemars        = { version = "0.8",  optional = true }
 subtle-encoding = { version = "0.5",  default-features = false }
 base64          = { version = "0.21", default-features = false, features = ["alloc"] }
 flex-error      = { version = "0.4",  default-features = false }
 ics23           = { version = "0.11.0", default-features = false }
+pbjson          = { version = "0.6.0", default-features = false }
```
Comment (Farhad-Shabani) [inline Cargo.toml]: We have some users in no-std environments, and the regular `pbjson` crate isn't cutting it there. Would you switch to the [`informalsystems-pbjson`](https://github.com/informalsystems/pbjson) instead? 
fyi: The `cosmos/ics2‍3` repo uses `informalsystems-pbjson` as well.

File: Cargo.toml [hunk 2]
```diff
@@ -32,11 +32,11 @@ prost           = { version = "0.12.3", default-features = false, features = ["p
 bytes           = { version = "1.2",  default-features = false }
 tonic           = { version = "0.10",  default-features = false, optional = true }
 serde           = { version = "1.0",  default-features = false, optional = true }
-schemars        = { version = "0.8",  optional = true }
```
Comment (Farhad-Shabani) [inline Cargo.toml:35]: Why the `jsonshcema` attributes have been discarded?

**Review by Farhad-Shabani — CHANGES_REQUESTED** [review]

File: Cargo.toml (hunk 1 above)
Comment (romac) [reply Cargo.toml]: Ah good point, I forgot we were using our fork for no-std support.

File: Cargo.toml (hunk 2 above)
Comment (grod220) [reply Cargo.toml:35]: Ah! This was in error. Mistakenly bundled this up with serde attr removals. It doesn't help that schemars and serde kinda look similar 😅 . Restored.

File: Cargo.toml (hunk 1 above)
Comment (grod220) [reply Cargo.toml]: Using the fork now 👍

File: tools/proto-compiler/src/cmd/compile.rs [hunk 3]
```diff
@@ -116,15 +121,11 @@ impl CompileCmd {
         // List available paths for dependencies
         let includes: Vec<PathBuf> = proto_includes_paths.iter().map(PathBuf::from).collect();
 
-        let attrs_serde =
-            r#"#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]"#;
-        let attrs_serde_default = r#"#[cfg_attr(feature = "serde", serde(default))]"#;
```
Comment (Farhad-Shabani) [inline tools/proto-compiler/src/cmd/compile.rs:121]: This `serde(default)` attribute derivation should be preserved as well. One notable use case: this enables ibc-rs to keep supporting chains on different proto versions where token transfer packet data may come with or without `memo` field, so [this test ](https://github.com/cosmos/ibc-rs/blob/8c1766fa823f8a2e8e83a79f39c521aa6e270a81/ibc-apps/ics20-transfer/types/src/packet.rs#L110-L115) shouldn't fail by our changes here.
To address this, I've tried `pbjson` builder with calling the `emit_fields()` which worked and resulted in the same behaviour as `attrs_serde_default`. Though this `emit_fields()` acts on all the proto types then. Please check this out on your end as well to ensure we won't be ending up with unexpected behaviours.

File: tools/proto-compiler/src/cmd/compile.rs [hunk 4]
```diff
@@ -140,81 +141,66 @@ impl CompileCmd {
...
+                //       After it's implemented there, we can delete these exclusions.
+                ".cosmos.base.abci.v1beta1",
+                ".cosmos.tx.v1beta1",
+                ".cosmos.base.tendermint.v1beta1",
+                ".interchain_security.ccv.v1",
+                ".interchain_security.ccv.provider.v1",
+                ".interchain_security.ccv.consumer.v1",
+                ".stride.interchainquery.v1",
+            ])
+            .build(&[
```
Comment (Farhad-Shabani) [inline tools/proto-compiler/src/cmd/compile.rs:194]:
```suggestion
            .emit_fields()
            .build(&[
```

**Review by Farhad-Shabani — CHANGES_REQUESTED** [review]

File: tools/proto-compiler/src/cmd/compile.rs (hunk 3 above)
Comment (grod220) [reply tools/proto-compiler/src/cmd/compile.rs:121]: If I understand this correctly, when serializing the struct, we want the json string to contain the default fields instead of omitting them entirely. Just added that compile option and two tests to ensure it's retained in the future.

Comment (grod220) [reply tools/proto-compiler/src/cmd/compile.rs:121]: Can you confirm this test case matches the use-case you mentioned? https://github.com/cosmos/ibc-proto-rs/blob/d6a737960db004f93612daeb25f7ca4d679a43cf/tests/test_serde_default.rs

File: tests/test_serde_default.rs [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+#[cfg(feature = "serde")]
+#[test]
+fn test_serde_can_serialize_defaults() {
+    let height = Height {
+        revision_number: 0u64,
+        revision_height: 0u64,
+    };
+    let str = serde_json::to_string(&height).unwrap();
+    assert_eq!(str, r#"{"revisionNumber":"0","revisionHeight":"0"}"#);
+}
```
Comment (Farhad-Shabani) [inline tests/test_serde_default.rs:25]:
```suggestion
}

#[cfg(feature = "serde")]
#[test]
fn test_serde_can_serialize_packet_data() {
    use ibc_proto::ibc::apps::transfer::v2::FungibleTokenPacketData;

    let packet_data = FungibleTokenPacketData {
        denom: "uatom".to_string(),
        amount: "10".to_string(),
        sender: "cosmos1wxeyh7zgn4tctjzs0vtqpc6p5cxq5t2muzl7ng".to_string(),
        receiver: "cosmos1wxeyh7zgn4tctjzs0vtqpc6p5cxq5t2muzl7ng".to_string(),
        memo: "".to_string(),
    };
    let str = serde_json::to_string(&packet_data).unwrap();
    assert_eq!(
        str,
        r#"{"denom":"uatom","amount":"10","sender":"cosmos1wxeyh7zgn4tctjzs0vtqpc6p5cxq5t2muzl7ng","receiver":"cosmos1wxeyh7zgn4tctjzs0vtqpc6p5cxq5t2muzl7ng","memo":""}"#
    );
}
```

File: tools/proto-compiler/src/cmd/compile.rs (hunk 3 above)
Comment (Farhad-Shabani) [reply tools/proto-compiler/src/cmd/compile.rs:121]: Exactly. You got it. 
By the way, I've added an additional test for the particular case of `TokenTransferPacketData`. So if we ever revisit the proto-compiler down the road, we'll get a heads-up on that.

Thank you @grod220 for addressing the comments! All set now from my end!

File: tests/test_serde_default.rs (hunk 5 above)
Comment (grod220) [reply tests/test_serde_default.rs:25]: Added 👍

**Review by Farhad-Shabani — APPROVED** [review]

**Comment by grod220** [comment]
@Farhad-Shabani thank you 🙏. Could we get a release published?

**Comment by romac** [comment]
https://github.com/cosmos/ibc-proto-rs/releases/tag/v0.40.0

Thanks @Farhad-Shabani!
